using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Medical_tools
{
    public partial class Form_Midical_Return : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        view_Medical_give_and_tool_2 view_Medical_Give_And_Tool_2 = new view_Medical_give_and_tool_2();
        TB_Midical_return tb_midical_return = new TB_Midical_return();
        TB_Medical_give tb_medical_give = new TB_Medical_give();
        public Form_Midical_Return()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Medical_give.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    edt_tool_give_tool_name.Properties.DataSource = dbContext.TB_Medical_give.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void Form_Midical_Return_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_FWDDataSet2060.TB_Medical_give' table. You can move, or remove it, as needed.
            this.tB_Medical_giveTableAdapter.Fill(this.dB_FWDDataSet2060.TB_Medical_give);

        }

        private void label12_Click(object sender, EventArgs e)
        {

        }

        private void edt_tool_give_tool_name_EditValueChanged(object sender, EventArgs e)
        {
            int RRt = Convert.ToInt32(edt_tool_give_tool_name.EditValue);
            view_Medical_Give_And_Tool_2 = DataBase.view_Medical_give_and_tool_2.Where(x => x.Medical_give_ID == RRt).FirstOrDefault();
           // edt_ssn_serch.Text = registered_rsers_view.Registered_Users_Ssn;
            Fill_labels_Data();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {

            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();



            tb_midical_return.Midical_return_tool = Convert.ToInt32(edt_tool_give_tool_name.EditValue);
            tb_midical_return.Midical_return_recever = Convert.ToInt32(edt_tool_give_emploee.EditValue);
            tb_midical_return.Midical_return_date = DateTime.Today;

            DataBase.TB_Midical_return.Add(tb_midical_return);
            DataBase.SaveChanges();

            try
            {
                tb_medical_give.Medical_give_ID = Convert.ToInt32(edt_tool_give_tool_name.EditValue);
                // Assign values to the specific columns you want to update
                tb_medical_give.Medical_give_return_status = "تم الارجاع";
                tb_medical_give.Medical_give_return_Date = DateTime.Today;

                // Attach the entity to the context
                DataBase.Set<TB_Medical_give>().Attach(tb_medical_give);

                // Mark only the modified columns as "Modified"
                var entry = DataBase.Entry(tb_medical_give);
                entry.Property(x => x.Medical_give_return_status).IsModified = true;
                entry.Property(x => x.Medical_give_return_Date).IsModified = true;

                DataBase.SaveChanges();

                ToastDone.LbTitelAlterBox.Text = "تم الارجاع ";
                ToastDone.Show();
                this.Close();
            }
            catch
            {
                ToastWaring.Lable_Text.Text = "حدث خطا , حاول مره اخرى";
                ToastWaring.Show();
            }


        }


        private void Fill_labels_Data()
        {

            try
            {
                label_C_Inf_name.Text = view_Medical_Give_And_Tool_2.Medical_tool_Name;
                label_C_Inf_ssn.Text = view_Medical_Give_And_Tool_2.Medical_give_recever;
                label_C_Inf_id.Text = view_Medical_Give_And_Tool_2.Medical_give_patient;
                label_C_Inf_add.Text = view_Medical_Give_And_Tool_2.Medical_give_date.ToString();               
            }
            catch
            {

            }


            // */
        }

    }
}
