using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Drawing.Drawing2D;
using System.Data.Entity;

namespace FWD.G_Medical_tools
{
    public partial class Form_Medical_Give : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_Medical_give tb_medical_give = new TB_Medical_give();
        public Form_Medical_Give()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext2 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext2.TB_Medical_tool.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                edt_tool_give_tool_name.Properties.DataSource = dbContext2.TB_Medical_tool.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());




            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBE_LOC.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    edt_tool_give_add.Properties.DataSource = dbContext.TBE_LOC.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void Form_Medical_Give_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_FWDDataSet2058.TBE_LOC' table. You can move, or remove it, as needed.
          //  this.tBE_LOCTableAdapter.Fill(this.dB_FWDDataSet2058.TBE_LOC);
            // TODO: This line of code loads data into the 'dB_FWDDataSet2057.TB_Medical_tool' table. You can move, or remove it, as needed.
        //    this.tB_Medical_toolTableAdapter.Fill(this.dB_FWDDataSet2057.TB_Medical_tool);
            MakePanelEdgesRound(panel1);

        }

        private void MakePanelEdgesRound(Panel panel)
        {
            int radius = 20;
            GraphicsPath path = new GraphicsPath();
            path.AddArc(panel.ClientRectangle.Width - radius, 0, radius, radius, 270, 90);
            path.AddArc(panel.ClientRectangle.Width - radius, panel.ClientRectangle.Height - radius, radius, radius, 0, 90);
            path.AddArc(0, panel.ClientRectangle.Height - radius, radius, radius, 90, 90);
            path.AddArc(0, 0, radius, radius, 180, 90);
            path.CloseFigure();
            panel.Region = new Region(path);
        }

        private void lookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();

            try
            {
                tb_medical_give.Medical_give_tool_Name = Convert.ToInt32(edt_tool_give_tool_name.EditValue);
                tb_medical_give.Medical_give_recever_ssn = edt_tool_give_ssn.Text;
                tb_medical_give.Medical_give_recever_phone = edt_tool_give_phone.Text;
                tb_medical_give.Medical_give_recever_add = Convert.ToInt32(edt_tool_give_add.EditValue);
                tb_medical_give.Medical_give_patient = edt_tool_give_pationt.Text;
                tb_medical_give.Medical_give_charity_recever = Class_main.emp_login_id;//Convert.ToInt32(edt_tool_give_emploee.EditValue);
                tb_medical_give.Medical_give_date = DateTime.Today;
                tb_medical_give.Medical_give_recever = edt_tool_give_recever.Text;
                tb_medical_give.Medical_give_return_status = "قيد الاستخدام";

                DataBase.TB_Medical_give.Add(tb_medical_give);
                DataBase.SaveChanges();

                ToastDone.LbTitelAlterBox.Text = "تمت عملية التسليم";
                ToastDone.Show();
                this.Close();
            }
            catch
            {
                ToastWaring.Lable_Text.Text = "حدث خطاء اثناء التسجيل";
                ToastWaring.Show();
            }

        }
    }
}
