//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FWDEntities : DbContext
    {
        public DB_FWDEntities()
            : base("name=DB_FWDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_AGR> TB_AGR { get; set; }
        public virtual DbSet<TB_BUS> TB_BUS { get; set; }
        public virtual DbSet<TB_Charity_info> TB_Charity_info { get; set; }
        public virtual DbSet<TB_Committee> TB_Committee { get; set; }
        public virtual DbSet<TB_Course_info> TB_Course_info { get; set; }
        public virtual DbSet<TB_CUS_Family_Member> TB_CUS_Family_Member { get; set; }
        public virtual DbSet<TB_CUS_Files> TB_CUS_Files { get; set; }
        public virtual DbSet<TB_CUS_Img> TB_CUS_Img { get; set; }
        public virtual DbSet<TB_CUST_Father> TB_CUST_Father { get; set; }
        public virtual DbSet<TB_CUST_Home> TB_CUST_Home { get; set; }
        public virtual DbSet<TB_CUST_Income> TB_CUST_Income { get; set; }
        public virtual DbSet<TB_CUST_Need> TB_CUST_Need { get; set; }
        public virtual DbSet<TB_CUST_Person> TB_CUST_Person { get; set; }
        public virtual DbSet<TB_CUST_Property> TB_CUST_Property { get; set; }
        public virtual DbSet<TB_CUST_Resercher> TB_CUST_Resercher { get; set; }
        public virtual DbSet<TB_DOC> TB_DOC { get; set; }
        public virtual DbSet<TB_Doctor_Info> TB_Doctor_Info { get; set; }
        public virtual DbSet<TB_DON> TB_DON { get; set; }
        public virtual DbSet<TB_Donation_Dirction> TB_Donation_Dirction { get; set; }
        public virtual DbSet<TB_Donner_info> TB_Donner_info { get; set; }
        public virtual DbSet<TB_Educational_Status> TB_Educational_Status { get; set; }
        public virtual DbSet<TB_Emploee> TB_Emploee { get; set; }
        public virtual DbSet<TB_Emploee_Roll> TB_Emploee_Roll { get; set; }
        public virtual DbSet<TB_Family_Needs_Type> TB_Family_Needs_Type { get; set; }
        public virtual DbSet<TB_Family_Owns_Type> TB_Family_Owns_Type { get; set; }
        public virtual DbSet<TB_FIN> TB_FIN { get; set; }
        public virtual DbSet<TB_General_report> TB_General_report { get; set; }
        public virtual DbSet<TB_Health_Status> TB_Health_Status { get; set; }
        public virtual DbSet<TB_Medical_give> TB_Medical_give { get; set; }
        public virtual DbSet<TB_Medical_tool> TB_Medical_tool { get; set; }
        public virtual DbSet<TB_Midical_return> TB_Midical_return { get; set; }
        public virtual DbSet<TB_PHAR> TB_PHAR { get; set; }
        public virtual DbSet<TB_Pharmasist_Info> TB_Pharmasist_Info { get; set; }
        public virtual DbSet<TB_POC> TB_POC { get; set; }
        public virtual DbSet<TB_PUR> TB_PUR { get; set; }
        public virtual DbSet<TB_Rank> TB_Rank { get; set; }
        public virtual DbSet<TB_Registered_Users> TB_Registered_Users { get; set; }
        public virtual DbSet<TB_RES> TB_RES { get; set; }
        public virtual DbSet<TB_SELL> TB_SELL { get; set; }
        public virtual DbSet<TB_Social_State> TB_Social_State { get; set; }
        public virtual DbSet<TB_SUPP> TB_SUPP { get; set; }
        public virtual DbSet<TB_Supscription_Moth> TB_Supscription_Moth { get; set; }
        public virtual DbSet<TB_Take_Course> TB_Take_Course { get; set; }
        public virtual DbSet<TB_User_Permitions> TB_User_Permitions { get; set; }
        public virtual DbSet<TB_volunteer> TB_volunteer { get; set; }
        public virtual DbSet<TB_Volunteer_Subscription> TB_Volunteer_Subscription { get; set; }
        public virtual DbSet<TB_Volunteer_Type> TB_Volunteer_Type { get; set; }
        public virtual DbSet<TB_WAT> TB_WAT { get; set; }
        public virtual DbSet<TB_WL_CAT> TB_WL_CAT { get; set; }
        public virtual DbSet<TBE_LOC> TBE_LOC { get; set; }
        public virtual DbSet<New_test_baisic> New_test_baisic { get; set; }
        public virtual DbSet<New_test_baisic_1> New_test_baisic_1 { get; set; }
        public virtual DbSet<Registered_Users_Search> Registered_Users_Search { get; set; }
        public virtual DbSet<Registered_Users_View> Registered_Users_View { get; set; }
        public virtual DbSet<View_CUST_Family> View_CUST_Family { get; set; }
        public virtual DbSet<View_CUST_Main_data_01> View_CUST_Main_data_01 { get; set; }
        public virtual DbSet<View_CUST_Need> View_CUST_Need { get; set; }
        public virtual DbSet<View_CUST_Propert> View_CUST_Propert { get; set; }
        public virtual DbSet<View_customer_main_data> View_customer_main_data { get; set; }
        public virtual DbSet<View_Doctor_Info> View_Doctor_Info { get; set; }
        public virtual DbSet<View_Doctor_report> View_Doctor_report { get; set; }
        public virtual DbSet<View_Donation_List_New> View_Donation_List_New { get; set; }
        public virtual DbSet<View_Donor> View_Donor { get; set; }
        public virtual DbSet<View_emploee_list> View_emploee_list { get; set; }
        public virtual DbSet<view_Emploee_login> view_Emploee_login { get; set; }
        public virtual DbSet<View_General_report> View_General_report { get; set; }
        public virtual DbSet<view_Medical_give_and_tool> view_Medical_give_and_tool { get; set; }
        public virtual DbSet<view_Medical_give_and_tool_2> view_Medical_give_and_tool_2 { get; set; }
        public virtual DbSet<View_Medical_Give_List> View_Medical_Give_List { get; set; }
        public virtual DbSet<View_Pharmasist_Info> View_Pharmasist_Info { get; set; }
        public virtual DbSet<view_Pharmasist_List> view_Pharmasist_List { get; set; }
        public virtual DbSet<View_Receive_Categroy> View_Receive_Categroy { get; set; }
        public virtual DbSet<View_Registered_Users> View_Registered_Users { get; set; }
        public virtual DbSet<View_Registered_Users_New> View_Registered_Users_New { get; set; }
        public virtual DbSet<View_Sell_to_Customers> View_Sell_to_Customers { get; set; }
        public virtual DbSet<View_supp_list> View_supp_list { get; set; }
        public virtual DbSet<View_Take_Course> View_Take_Course { get; set; }
        public virtual DbSet<view_volanteer> view_volanteer { get; set; }
        public virtual DbSet<View_Volunteer_Subscription> View_Volunteer_Subscription { get; set; }
        public virtual DbSet<View_Wating_List_List> View_Wating_List_List { get; set; }
        public virtual DbSet<View_Whating_List_Date> View_Whating_List_Date { get; set; }
        public virtual DbSet<ViewTemp_2> ViewTemp_2 { get; set; }
        public virtual DbSet<View_reserchers2> View_reserchers2 { get; set; }
    }
}
