//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AGR
    {
        public int ID { get; set; }
        public string AGR_Type { get; set; }
        public Nullable<int> AGR_Amount { get; set; }
        public string AGR_Amount_Text { get; set; }
        public string AGR_Charity_Num { get; set; }
        public string AGR_From { get; set; }
        public string AGR_From_SSN { get; set; }
        public string AGR_BOX { get; set; }
    }
}
