//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BUS
    {
        public int ID { get; set; }
        public string BUS_Cap { get; set; }
        public Nullable<int> BUS_Pationt { get; set; }
        public Nullable<System.DateTime> BUS_Date { get; set; }
        public string BUS_Det { get; set; }
    
        public virtual TB_Registered_Users TB_Registered_Users { get; set; }
    }
}
