//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUST_Home
    {
        public int CUST_Home_ID { get; set; }
        public string CUST_Home_Own { get; set; }
        public Nullable<int> CUST_Home_Room_Num { get; set; }
        public Nullable<int> CUST_Home_Floor_Num { get; set; }
        public string CUST_Home_Struct_Type { get; set; }
        public string CUST_Home_Floor_Type { get; set; }
        public string CUST_Home_Ceil_Type { get; set; }
        public Nullable<bool> CUST_Home_Elec { get; set; }
        public Nullable<bool> CUST_Home_Water { get; set; }
        public Nullable<bool> CUST_Home_WC { get; set; }
        public Nullable<bool> CUST_Home_Gas { get; set; }
        public Nullable<bool> CUST_Home_Frizer { get; set; }
        public Nullable<bool> CUST_Home_cooler { get; set; }
        public Nullable<bool> CUST_Home_washing { get; set; }
        public Nullable<bool> CUST_Home_Botogaz { get; set; }
        public Nullable<bool> CUST_Home_AC { get; set; }
        public Nullable<bool> CUST_Home_TV { get; set; }
        public Nullable<bool> CUST_Home_Cooker { get; set; }
        public string CUST_Home_More_Info { get; set; }
        public Nullable<int> CUST_Home_PK { get; set; }
        public Nullable<int> CUST_Home_Add { get; set; }
        public string CUST_Home_Add_Det { get; set; }
    
        public virtual TB_CUST_Person TB_CUST_Person { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
    }
}
