//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Charity_info
    {
        public int Charity_info_ID { get; set; }
        public string Charity_info_Name { get; set; }
        public string Charity_info_Domain { get; set; }
        public Nullable<int> Charity_info_Manager { get; set; }
    }
}
