//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUST_Father
    {
        public int Father_ID { get; set; }
        public string CUST_Father_Name { get; set; }
        public string CUST_Father_SSN { get; set; }
        public Nullable<int> CUST_Father_Edu { get; set; }
        public Nullable<System.DateTime> CUST_Father_Bairth { get; set; }
        public Nullable<int> CUST_Father_Age { get; set; }
        public Nullable<int> CUST_Father_helth { get; set; }
        public string CUST_Father_Helth_det { get; set; }
        public string CUST_Father_Phone { get; set; }
        public Nullable<int> CUST_Father_FK { get; set; }
    
        public virtual TB_CUST_Person TB_CUST_Person { get; set; }
        public virtual TB_Educational_Status TB_Educational_Status { get; set; }
        public virtual TB_Health_Status TB_Health_Status { get; set; }
    }
}
