//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUST_Income
    {
        public int CUST_Income_ID { get; set; }
        public string CUST_Income_Owner { get; set; }
        public string CUST_Income_State { get; set; }
        public string CUST_Income_Type { get; set; }
        public string CUST_Income_Name { get; set; }
        public Nullable<double> CUST_Income_Value { get; set; }
        public Nullable<int> CUST_Income_PK { get; set; }
    
        public virtual TB_CUST_Person TB_CUST_Person { get; set; }
    }
}
