//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUS_Family_Member
    {
        public int CUST_Family_ID { get; set; }
        public string CUST_Family_Member_Name { get; set; }
        public string CUST_Family_Member_Relation { get; set; }
        public string CUST_Family_Member_SSN { get; set; }
        public Nullable<int> CUST_Family_Member_Age { get; set; }
        public Nullable<System.DateTime> CUST_Family_Member_Bairth { get; set; }
        public Nullable<int> CUST_Family_Member_So_St { get; set; }
        public Nullable<int> CUST_Family_Member_Edu { get; set; }
        public Nullable<int> CUST_Family_Member_Helth { get; set; }
        public string CUST_Family_Member_Helth_det { get; set; }
        public Nullable<int> CUST_Family_Member_PK { get; set; }
    
        public virtual TB_CUST_Person TB_CUST_Person { get; set; }
        public virtual TB_Educational_Status TB_Educational_Status { get; set; }
        public virtual TB_Health_Status TB_Health_Status { get; set; }
        public virtual TB_Social_State TB_Social_State { get; set; }
    }
}
