//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUST_Need
    {
        public int CUST_Need_ID { get; set; }
        public Nullable<int> CUST_Need_Type { get; set; }
        public string CUST_Need_type_det { get; set; }
        public Nullable<int> CUST_Need_FK { get; set; }
    
        public virtual TB_CUST_Person TB_CUST_Person { get; set; }
        public virtual TB_Family_Needs_Type TB_Family_Needs_Type { get; set; }
    }
}
