//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CUST_Property
    {
        public int CUST_Property_ID { get; set; }
        public Nullable<int> CUST_Property_Name { get; set; }
        public Nullable<double> CUST_Property_value { get; set; }
        public string CUST_Property_Det { get; set; }
        public Nullable<int> CUST_Property_PK { get; set; }
    
        public virtual TB_CUST_Person TB_CUST_Person { get; set; }
        public virtual TB_Family_Owns_Type TB_Family_Owns_Type { get; set; }
    }
}
