//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DON
    {
        public int ID { get; set; }
        public Nullable<int> DON_Name { get; set; }
        public Nullable<int> DON_Dir { get; set; }
        public Nullable<double> DON_Amount { get; set; }
        public string DON_Amo_txt { get; set; }
        public Nullable<int> DON_Resever { get; set; }
        public Nullable<System.DateTime> DON_Date { get; set; }
    
        public virtual TB_Donation_Dirction TB_Donation_Dirction { get; set; }
        public virtual TB_Donner_info TB_Donner_info { get; set; }
        public virtual TB_Emploee TB_Emploee { get; set; }
    }
}
