//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Doctor_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Doctor_Info()
        {
            this.TB_DOC = new HashSet<TB_DOC>();
        }
    
        public int Doctor_ID { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_spicailize { get; set; }
        public Nullable<int> Doctor_Add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOC> TB_DOC { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
    }
}
