//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Emploee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Emploee()
        {
            this.TB_DON = new HashSet<TB_DON>();
            this.TB_General_report = new HashSet<TB_General_report>();
            this.TB_Medical_give = new HashSet<TB_Medical_give>();
            this.TB_SELL = new HashSet<TB_SELL>();
        }
    
        public int Emploee_ID { get; set; }
        public string Emploee_Name { get; set; }
        public string Emploee_UserName { get; set; }
        public string Emploee_Password { get; set; }
        public string Emploee_phone { get; set; }
        public Nullable<int> Emploee_Roll { get; set; }
        public string Emploee_Roll_login_State { get; set; }
        public Nullable<int> Emploee_permitions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DON> TB_DON { get; set; }
        public virtual TB_Emploee_Roll TB_Emploee_Roll { get; set; }
        public virtual TB_User_Permitions TB_User_Permitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_General_report> TB_General_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Medical_give> TB_Medical_give { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SELL> TB_SELL { get; set; }
    }
}
