//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_General_report
    {
        public int General_report_ID { get; set; }
        public Nullable<int> General_report_Number { get; set; }
        public string General_report_day { get; set; }
        public Nullable<System.DateTime> General_report_date { get; set; }
        public string General_report_start { get; set; }
        public string General_report_end { get; set; }
        public string General_report_table { get; set; }
        public string General_report_dessition { get; set; }
        public string General_report_attend { get; set; }
        public Nullable<System.DateTime> General_report_create_date { get; set; }
        public Nullable<int> General_report_writer { get; set; }
    
        public virtual TB_Emploee TB_Emploee { get; set; }
    }
}
