//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Medical_give
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Medical_give()
        {
            this.TB_Midical_return = new HashSet<TB_Midical_return>();
        }
    
        public int Medical_give_ID { get; set; }
        public Nullable<int> Medical_give_tool_Name { get; set; }
        public string Medical_give_patient { get; set; }
        public string Medical_give_recever { get; set; }
        public string Medical_give_recever_ssn { get; set; }
        public string Medical_give_recever_phone { get; set; }
        public Nullable<int> Medical_give_recever_add { get; set; }
        public Nullable<int> Medical_give_charity_recever { get; set; }
        public Nullable<System.DateTime> Medical_give_date { get; set; }
        public string Medical_give_return_status { get; set; }
        public Nullable<System.DateTime> Medical_give_return_Date { get; set; }
    
        public virtual TB_Emploee TB_Emploee { get; set; }
        public virtual TB_Medical_tool TB_Medical_tool { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Midical_return> TB_Midical_return { get; set; }
    }
}
