//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Medical_tool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Medical_tool()
        {
            this.TB_Medical_give = new HashSet<TB_Medical_give>();
        }
    
        public int Medical_tool_ID { get; set; }
        public string Medical_tool_Name { get; set; }
        public string Medical_tool_owner { get; set; }
        public byte[] Medical_tool_image { get; set; }
        public string Medical_tool_info { get; set; }
        public Nullable<int> Medical_tool_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Medical_give> TB_Medical_give { get; set; }
    }
}
