//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pharmasist_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Pharmasist_Info()
        {
            this.TB_PHAR = new HashSet<TB_PHAR>();
        }
    
        public int Pharmasist_ID { get; set; }
        public string Pharmasist_Name { get; set; }
        public Nullable<int> Pharmasist_Add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PHAR> TB_PHAR { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
    }
}
