//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PHAR
    {
        public int ID { get; set; }
        public Nullable<int> PHR_Doctor { get; set; }
        public string PHR_Drug { get; set; }
        public Nullable<int> PHR_Patint { get; set; }
        public Nullable<System.DateTime> PHR_Date { get; set; }
    
        public virtual TB_Pharmasist_Info TB_Pharmasist_Info { get; set; }
        public virtual TB_Registered_Users TB_Registered_Users { get; set; }
    }
}
