//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Registered_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Registered_Users()
        {
            this.TB_BUS = new HashSet<TB_BUS>();
            this.TB_DOC = new HashSet<TB_DOC>();
            this.TB_PHAR = new HashSet<TB_PHAR>();
            this.TB_SELL = new HashSet<TB_SELL>();
            this.TB_Take_Course = new HashSet<TB_Take_Course>();
        }
    
        public int Registered_Users_ID { get; set; }
        public string Registered_Users_Name { get; set; }
        public Nullable<int> Registered_Users_so_st { get; set; }
        public string Registered_Users_Ssn { get; set; }
        public string Registered_Users_Hus_Name { get; set; }
        public string Registered_Users_Hus_Ssn { get; set; }
        public string Registered_Users_Hus_Phone { get; set; }
        public string Registered_Users_phone { get; set; }
        public Nullable<int> Registered_Users_Fam_Num { get; set; }
        public Nullable<int> Registered_Users_Add { get; set; }
        public string Registered_Users_Add_det { get; set; }
        public string Registered_Users_incom_name { get; set; }
        public Nullable<double> Registered_Users_income_val { get; set; }
        public Nullable<int> Registered_Users_Supp { get; set; }
        public Nullable<int> Registered_Users_Rank { get; set; }
        public Nullable<int> Registered_Users_Helth { get; set; }
        public string Registered_Users_Helth_info { get; set; }
        public Nullable<System.DateTime> Registered_Users_BairthDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BUS> TB_BUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DOC> TB_DOC { get; set; }
        public virtual TB_Health_Status TB_Health_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PHAR> TB_PHAR { get; set; }
        public virtual TB_Rank TB_Rank { get; set; }
        public virtual TB_Social_State TB_Social_State { get; set; }
        public virtual TB_SUPP TB_SUPP { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SELL> TB_SELL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Take_Course> TB_Take_Course { get; set; }
    }
}
