//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_RES()
        {
            this.TB_CUST_Resercher = new HashSet<TB_CUST_Resercher>();
        }
    
        public int ID { get; set; }
        public string RES_Name { get; set; }
        public Nullable<int> RES_Add { get; set; }
        public string RES_SSN { get; set; }
        public string RES_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CUST_Resercher> TB_CUST_Resercher { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
    }
}
