//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SUPP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SUPP()
        {
            this.TB_CUST_Resercher = new HashSet<TB_CUST_Resercher>();
            this.TB_Registered_Users = new HashSet<TB_Registered_Users>();
            this.TB_WAT = new HashSet<TB_WAT>();
        }
    
        public int ID { get; set; }
        public string SUPP_Name { get; set; }
        public Nullable<int> SUPP_Adress { get; set; }
        public string SUPP_SSN { get; set; }
        public string SUPP_Phone1 { get; set; }
        public string SUPP_phone2 { get; set; }
        public Nullable<int> SUPP_Retion { get; set; }
        public Nullable<System.DateTime> SUPP_Bairth { get; set; }
        public Nullable<System.DateTime> SUPP_Date_Regest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CUST_Resercher> TB_CUST_Resercher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Registered_Users> TB_Registered_Users { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
        public virtual TBE_LOC TBE_LOC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WAT> TB_WAT { get; set; }
    }
}
