//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Take_Course
    {
        public int Take_Course_ID { get; set; }
        public Nullable<int> Take_Course_Course { get; set; }
        public Nullable<int> Take_Course_Student { get; set; }
    
        public virtual TB_Course_info TB_Course_info { get; set; }
        public virtual TB_Registered_Users TB_Registered_Users { get; set; }
    }
}
