//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_User_Permitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_User_Permitions()
        {
            this.TB_Emploee = new HashSet<TB_Emploee>();
        }
    
        public int Permition_ID { get; set; }
        public Nullable<bool> Wat_list_list { get; set; }
        public Nullable<bool> Wat_list_add { get; set; }
        public Nullable<bool> Wat_list_del { get; set; }
        public Nullable<bool> Wat_list_edit { get; set; }
        public Nullable<bool> Receve_list { get; set; }
        public Nullable<bool> Receve_add { get; set; }
        public Nullable<bool> Receve_del { get; set; }
        public Nullable<bool> Supp_list { get; set; }
        public Nullable<bool> Supp_add { get; set; }
        public Nullable<bool> Supp_del { get; set; }
        public Nullable<bool> Supp_edit { get; set; }
        public Nullable<bool> Category_list { get; set; }
        public Nullable<bool> Category_add { get; set; }
        public Nullable<bool> Category_del { get; set; }
        public Nullable<bool> Category_edit { get; set; }
        public Nullable<bool> Donation_List { get; set; }
        public Nullable<bool> Donation_del { get; set; }
        public Nullable<bool> Poket_list { get; set; }
        public Nullable<bool> Poket_del { get; set; }
        public Nullable<bool> Volanteer_list { get; set; }
        public Nullable<bool> volanteer_add { get; set; }
        public Nullable<bool> volanteer_edit { get; set; }
        public Nullable<bool> volanteer_subscription { get; set; }
        public Nullable<bool> Doctor_add { get; set; }
        public Nullable<bool> Doctor_doc_add { get; set; }
        public Nullable<bool> Doctor_del { get; set; }
        public Nullable<bool> Doctor_doc_del { get; set; }
        public Nullable<bool> Pharmasy_add { get; set; }
        public Nullable<bool> Pharmasy_doc_add { get; set; }
        public Nullable<bool> Pharmasy_del { get; set; }
        public Nullable<bool> Pharmasy_doc_del { get; set; }
        public Nullable<bool> Record_lisr { get; set; }
        public Nullable<bool> Record_add { get; set; }
        public Nullable<bool> Record_del { get; set; }
        public Nullable<bool> Record_edit { get; set; }
        public Nullable<bool> Course_list { get; set; }
        public Nullable<bool> Course_add { get; set; }
        public Nullable<bool> Course_edit { get; set; }
        public Nullable<bool> Course_del { get; set; }
        public Nullable<bool> Trainer_add { get; set; }
        public Nullable<bool> Trainer_list { get; set; }
        public Nullable<bool> Trainer_edit { get; set; }
        public Nullable<bool> Trainer_del { get; set; }
        public Nullable<bool> Midical_List_add { get; set; }
        public Nullable<bool> Midical_List_list { get; set; }
        public Nullable<bool> Midical_List_del { get; set; }
        public Nullable<bool> Midical_List_edit { get; set; }
        public Nullable<bool> Midical_Receve_return { get; set; }
        public Nullable<bool> Midical_Receve_add { get; set; }
        public Nullable<bool> Midical_Receve_del { get; set; }
        public Nullable<bool> Midical_Receve_edit { get; set; }
        public Nullable<bool> General_report_add { get; set; }
        public Nullable<bool> General_report_edit { get; set; }
        public Nullable<bool> General_report_list { get; set; }
        public Nullable<bool> General_report_del { get; set; }
        public Nullable<bool> General_user_list { get; set; }
        public Nullable<bool> General_user_add { get; set; }
        public Nullable<bool> General_server { get; set; }
        public Nullable<bool> General_backup { get; set; }
        public Nullable<bool> General_user_del { get; set; }
        public Nullable<bool> Donation_Donnner { get; set; }
        public Nullable<bool> General_programe_set { get; set; }
        public Nullable<bool> General_home { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Emploee> TB_Emploee { get; set; }
    }
}
