//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_volunteer()
        {
            this.TB_Volunteer_Subscription = new HashSet<TB_Volunteer_Subscription>();
        }
    
        public int volunteer_ID { get; set; }
        public string volunteer_Name { get; set; }
        public string volunteer_SSN { get; set; }
        public string volunteer_Phone { get; set; }
        public Nullable<int> volunteer_Department_1 { get; set; }
        public Nullable<int> volunteer_Department_2 { get; set; }
        public Nullable<int> volunteer_type { get; set; }
        public string volunteer_type_num { get; set; }
        public Nullable<int> volunteer_Add { get; set; }
        public Nullable<int> volunteer_Work_add { get; set; }
        public Nullable<double> volunteer_Tax { get; set; }
        public string volunteer_Jop { get; set; }
        public string volunteer_more_info { get; set; }
        public Nullable<System.DateTime> volunteer_Start_Date { get; set; }
        public Nullable<System.DateTime> volunteer_Bairth { get; set; }
        public Nullable<int> volunteer_sol_st { get; set; }
    
        public virtual TB_Committee TB_Committee { get; set; }
        public virtual TB_Committee TB_Committee1 { get; set; }
        public virtual TB_Social_State TB_Social_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Volunteer_Subscription> TB_Volunteer_Subscription { get; set; }
        public virtual TB_Volunteer_Type TB_Volunteer_Type { get; set; }
        public virtual TBE_LOC TBE_LOC { get; set; }
        public virtual TBE_LOC TBE_LOC1 { get; set; }
    }
}
