//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBE_LOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBE_LOC()
        {
            this.TB_CUST_Home = new HashSet<TB_CUST_Home>();
            this.TB_Doctor_Info = new HashSet<TB_Doctor_Info>();
            this.TB_Donner_info = new HashSet<TB_Donner_info>();
            this.TB_Donner_info1 = new HashSet<TB_Donner_info>();
            this.TB_Medical_give = new HashSet<TB_Medical_give>();
            this.TB_Pharmasist_Info = new HashSet<TB_Pharmasist_Info>();
            this.TB_Registered_Users = new HashSet<TB_Registered_Users>();
            this.TB_RES = new HashSet<TB_RES>();
            this.TB_SUPP = new HashSet<TB_SUPP>();
            this.TB_SUPP1 = new HashSet<TB_SUPP>();
            this.TB_volunteer = new HashSet<TB_volunteer>();
            this.TB_volunteer1 = new HashSet<TB_volunteer>();
            this.TB_WAT = new HashSet<TB_WAT>();
        }
    
        public int ID { get; set; }
        public string LOC_Name { get; set; }
        public string LOC_Key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CUST_Home> TB_CUST_Home { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Doctor_Info> TB_Doctor_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Donner_info> TB_Donner_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Donner_info> TB_Donner_info1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Medical_give> TB_Medical_give { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Pharmasist_Info> TB_Pharmasist_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Registered_Users> TB_Registered_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RES> TB_RES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SUPP> TB_SUPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SUPP> TB_SUPP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_volunteer> TB_volunteer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_volunteer> TB_volunteer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WAT> TB_WAT { get; set; }
    }
}
