//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Receive_Categroy
    {
        public int ID { get; set; }
        public string Registered_Users_Name { get; set; }
        public string Registered_Users_Ssn { get; set; }
        public string Registered_Users_phone { get; set; }
        public string SELL_Resv_Name { get; set; }
        public string PUR_Name { get; set; }
        public Nullable<System.DateTime> SELL_Date { get; set; }
        public Nullable<int> SELL_Num { get; set; }
    }
}
