//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Pharmasist_Info
    {
        public int Pharmasist_ID { get; set; }
        public string Pharmasist_Name { get; set; }
        public string LOC_Name { get; set; }
    }
}
