//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Medical_give_and_tool
    {
        public int Medical_give_ID { get; set; }
        public string Medical_tool_Name { get; set; }
        public string Medical_give_patient { get; set; }
        public Nullable<System.DateTime> Medical_give_date { get; set; }
    }
}
