//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CUST_Family
    {
        public int CUST_Family_ID { get; set; }
        public string CUST_Family_Member_Name { get; set; }
        public string CUST_Family_Member_Relation { get; set; }
        public string CUST_Family_Member_SSN { get; set; }
        public Nullable<System.DateTime> CUST_Family_Member_Bairth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Social_State_Name { get; set; }
        public string Educational_Status_Name { get; set; }
        public string Health_Status_Name { get; set; }
        public string CUST_Family_Member_Helth_det { get; set; }
        public Nullable<int> CUST_Family_Member_PK { get; set; }
        public string CUST_Person_Name { get; set; }
    }
}
