//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Pharmasist_List
    {
        public int ID { get; set; }
        public string Pharmasist_Name { get; set; }
        public string Registered_Users_Name { get; set; }
        public string Registered_Users_Ssn { get; set; }
        public string Registered_Users_phone { get; set; }
        public string PHR_Drug { get; set; }
        public Nullable<int> PHR_Patint { get; set; }
        public Nullable<System.DateTime> PHR_Date { get; set; }
    }
}
