//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_supp_list
    {
        public int ID { get; set; }
        public string SUPP_Name { get; set; }
        public string SUPP_SSN { get; set; }
        public string SUPP_Phone1 { get; set; }
        public string SUPP_phone2 { get; set; }
        public Nullable<System.DateTime> SUPP_Bairth { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> SUPP_Date_Regest { get; set; }
        public string supp_Add { get; set; }
        public string SUPP_Retion_Add { get; set; }
    }
}
