//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Whating_List_Date
    {
        public int ID { get; set; }
        public string WAT_Name { get; set; }
        public Nullable<int> WAT_Cat { get; set; }
        public string WAT_SSN { get; set; }
        public Nullable<int> WAT_Add { get; set; }
        public string WAT_Phone1 { get; set; }
        public string WAT_Phone2 { get; set; }
        public Nullable<int> WAT_Supp_name { get; set; }
        public string WAT_Supp_Phone { get; set; }
        public string WAT_Det { get; set; }
        public Nullable<System.DateTime> WAT_Date_Order { get; set; }
        public string WAT_Done_state { get; set; }
        public Nullable<System.DateTime> WAT_Done_Date { get; set; }
        public Nullable<System.DateTime> WAT_Date_Bairth { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
