//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Take_Course
    {
        public int Take_Course_ID { get; set; }
        public string Registered_Users_Name { get; set; }
        public string Registered_Users_ssn { get; set; }
        public string Registered_Users_phone { get; set; }
        public string Course_Name { get; set; }
        public Nullable<System.DateTime> Course_start { get; set; }
        public Nullable<System.DateTime> Course_end { get; set; }
        public Nullable<double> Course_Price { get; set; }
        public Nullable<int> Take_Course_Course { get; set; }
        public Nullable<int> Take_Course_Student { get; set; }
    }
}
