//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Volunteer_Subscription
    {
        public int Volunteer_Subscription_ID { get; set; }
        public string volunteer_Name { get; set; }
        public string volunteer_SSN { get; set; }
        public string volunteer_Phone { get; set; }
        public Nullable<int> volunteer_Department_1 { get; set; }
        public Nullable<double> Volunteer_Subscription_Value { get; set; }
        public Nullable<int> Volunteer_Subscription_recet_num { get; set; }
        public Nullable<System.DateTime> Volunteer_Subscription_Date { get; set; }
        public string Moth_Name { get; set; }
        public Nullable<int> Volunteer_Subscription_FK { get; set; }
    }
}
