//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Registered_Users_New
    {
        public int Registered_Users_ID { get; set; }
        public string Registered_Users_Name { get; set; }
        public string Social_State_Name { get; set; }
        public string Registered_Users_Ssn { get; set; }
        public string Registered_Users_Hus_Name { get; set; }
        public string Registered_Users_Hus_Ssn { get; set; }
        public string Registered_Users_Hus_Phone { get; set; }
        public string Registered_Users_phone { get; set; }
        public Nullable<int> Registered_Users_Fam_Num { get; set; }
        public string Registered_Users_Add_det { get; set; }
        public string LOC_Name { get; set; }
        public string Registered_Users_incom_name { get; set; }
        public Nullable<double> Registered_Users_income_val { get; set; }
        public string SUPP_Name { get; set; }
        public string Rank_Name { get; set; }
        public string Health_Status_Name { get; set; }
        public string Registered_Users_Helth_info { get; set; }
        public Nullable<System.DateTime> Registered_Users_BairthDay { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
