//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CUST_Propert
    {
        public int CUST_Property_ID { get; set; }
        public string Family_Owns_Type_Name { get; set; }
        public Nullable<double> CUST_Property_value { get; set; }
        public string CUST_Property_Det { get; set; }
        public Nullable<int> CUST_Property_PK { get; set; }
    }
}
