//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_customer_main_data
    {
        public int CUST_Main_ID { get; set; }
        public string CUST_Person_Name { get; set; }
        public string CUST_Person_SSN { get; set; }
        public Nullable<int> CUST_Person_SO_ST { get; set; }
        public string CUST_Person_Gen { get; set; }
        public string person_Educational_Status_Name { get; set; }
        public Nullable<System.DateTime> CUST_Person_Bairth { get; set; }
        public Nullable<int> Age_person { get; set; }
        public string person_Health_Status_Name { get; set; }
        public string CUST_Person_Helth_Det { get; set; }
        public string CUST_Person_Phone_1 { get; set; }
        public string CUST_Person_Phone_2 { get; set; }
        public string CUST_Father_Name { get; set; }
        public string CUST_Father_SSN { get; set; }
        public Nullable<int> CUST_Father_Edu { get; set; }
        public string Father_Educational_Status_Name { get; set; }
        public Nullable<System.DateTime> CUST_Father_Bairth { get; set; }
        public Nullable<int> Age_father { get; set; }
        public Nullable<int> CUST_Father_helth { get; set; }
        public string Father_Health_Status_Name { get; set; }
        public string CUST_Father_Helth_det { get; set; }
        public string CUST_Father_Phone { get; set; }
        public string CUST_Home_Own { get; set; }
        public Nullable<int> CUST_Home_Room_Num { get; set; }
        public Nullable<int> CUST_Home_Floor_Num { get; set; }
        public string CUST_Home_Struct_Type { get; set; }
        public string CUST_Home_Floor_Type { get; set; }
        public string CUST_Home_Ceil_Type { get; set; }
        public Nullable<bool> CUST_Home_Elec { get; set; }
        public Nullable<bool> CUST_Home_Water { get; set; }
        public Nullable<bool> CUST_Home_WC { get; set; }
        public Nullable<bool> CUST_Home_Gas { get; set; }
        public Nullable<bool> CUST_Home_Frizer { get; set; }
        public Nullable<bool> CUST_Home_cooler { get; set; }
        public Nullable<bool> CUST_Home_washing { get; set; }
        public Nullable<bool> CUST_Home_Botogaz { get; set; }
        public Nullable<bool> CUST_Home_AC { get; set; }
        public Nullable<bool> CUST_Home_TV { get; set; }
        public Nullable<bool> CUST_Home_Cooker { get; set; }
        public string CUST_Home_More_Info { get; set; }
        public string LOC_Name { get; set; }
        public string CUST_Home_Add_Det { get; set; }
        public Nullable<int> CUST_Resercher_Name { get; set; }
        public Nullable<System.DateTime> CUST_Resercher_Date { get; set; }
        public Nullable<int> CUST_Resercher_Supp { get; set; }
        public string CUST_Resercher_Direction { get; set; }
        public Nullable<int> CUST_Resercher_Deg { get; set; }
        public string Rank_Name { get; set; }
        public string CUST_Resercher_Opin { get; set; }
    }
}
