//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWD
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Donation_List_New
    {
        public int ID { get; set; }
        public string Donner_Name { get; set; }
        public string Donner_Phone { get; set; }
        public string Donation_Dir_Name { get; set; }
        public Nullable<double> DON_Amount { get; set; }
        public string DON_Amo_txt { get; set; }
        public string Emploee_Name { get; set; }
        public Nullable<System.DateTime> DON_Date { get; set; }
    }
}
