using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Registered_Users
{
    public partial class Form_Search_Person : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();

        public Form_Search_Person()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Registered_Users_Search.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.Registered_Users_Search.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void textEdit2_EditValueChanged(object sender, EventArgs e)
        {
            edit_ssn.Text = "";
            var search_ssn = Edit_name.Text;
            gridControl1.DataSource = DataBase.Registered_Users_Search.Where(x => x.Registered_Users_Name.Contains(search_ssn)).ToList();
        }

        private void Form_Search_Person_Load(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            var search_ssn = edit_ssn.Text;
            gridControl1.DataSource = DataBase.Registered_Users_Search.Where(x => x.Registered_Users_Ssn.Contains(search_ssn)).ToList();
        }

        private void edit_ssn_EditValueChanged(object sender, EventArgs e)
        {
            Edit_name.Text = "";
            var search_ssn = edit_ssn.Text;
            gridControl1.DataSource = DataBase.Registered_Users_Search.Where(x => x.Registered_Users_Ssn.Contains(search_ssn)).ToList();
        }

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            G_Registered_Users.Form_Registered_Users_Add form_registered_users_add = new G_Registered_Users.Form_Registered_Users_Add();
            form_registered_users_add.Show();
            this.Close();
        }
    }
}
