using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Courses
{
    public partial class Form_Courses_List : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_Course_info tb_course_info = new TB_Course_info();
        public Form_Courses_List()
        {
            Lood_List_Data();
           
        }

        private void btn_edt_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Course_ID"));

            G_Courses.Form_Courses_Add form_courses_add = new Form_Courses_Add();
            tb_course_info = DataBase.TB_Course_info.Where(x => x.Course_ID == id).FirstOrDefault();

            form_courses_add.ID_course = id;
            form_courses_add.Add.Text = "تعديل";

            form_courses_add.edt_course_name.Text = tb_course_info.Course_Name;
            form_courses_add.edt_course_teacher.Text = tb_course_info.Course_teraner;
            form_courses_add.edt_course_start.DateTimeOffset = tb_course_info.Course_start.Value;
            form_courses_add.edt_course_end.DateTimeOffset = tb_course_info.Course_end.Value;
            form_courses_add.edt_course_owner.Text = tb_course_info.Course_owner;
            form_courses_add.edt_course_teacher_cost.Text = tb_course_info.Course_teatcher_cost.ToString();
            form_courses_add.edt_course_price.Text = tb_course_info.Course_Price.ToString();
            form_courses_add.edt_course_student_tax.Text = tb_course_info.Course_studet_tax.ToString();
            form_courses_add.edt_course_manager.Text = tb_course_info.Course_treener_manager;
            form_courses_add.edt_course_location.Text = tb_course_info.Course_location;
            form_courses_add.edt_course_info.Text = tb_course_info.Course_more_info;
            form_courses_add.edt_course_phone.Text = tb_course_info.Course_teacher_phone;
            form_courses_add.edt_course_trenee_num.Text = tb_course_info.Course_student_num.ToString();


            form_courses_add.Show();

        }

        void Lood_List_Data()
        {
            InitializeComponent();
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            dbContext.TB_Course_info.LoadAsync().ContinueWith(loadTask => {
                gridControl1.DataSource = dbContext.TB_Course_info.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Course_info.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Course_info.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btn_ref_Click(object sender, EventArgs e){   
          
            UpDate_Data();
        }
        private void UpDate_Data()
        {
            DataBase = new DB_FWDEntities();
            gridControl1.DataSource = DataBase.TB_Course_info.ToList();
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من عملية الحذف", MessageBoxButtons.YesNo);

            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            Toast.Toast_Del ToastDel = new Toast.Toast_Del();


            try
            {
                if (rs == DialogResult.Yes)
                {
                    tb_course_info = DataBase.TB_Course_info.Where(x => x.Course_ID == id).FirstOrDefault();
                    DataBase.Entry(tb_course_info).State = EntityState.Deleted;
                    DataBase.SaveChanges();
                    UpDate_Data();

                    ToastDel.Show();
                }
            }
            catch
            {
                ToastWaring.Lable_Text.Text = "لا يوجد شئ لحذفة";
                ToastWaring.Show();
            }
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
