using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Courses
{
    public partial class Form_Take_Course_List : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();

        View_Take_Course view_take_course = new View_Take_Course();
        TB_Take_Course tB_Take_Course = new TB_Take_Course();
        public Form_Take_Course_List()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.View_Take_Course.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.View_Take_Course.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            // This line of code is generated by Data Source Configuration Wizard
         
        }

        private void btn_ref_Click(object sender, EventArgs e)
        {
            DataBase = new DB_FWDEntities();
            gridControl1.DataSource = DataBase.View_Take_Course.ToList();
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من عملية الحذف", MessageBoxButtons.YesNo);

            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            Toast.Toast_Del ToastDel = new Toast.Toast_Del();


            try
            {
                if (rs == DialogResult.Yes)
                {
                    tB_Take_Course = DataBase.TB_Take_Course.Where(x => x.Take_Course_ID == id).FirstOrDefault();
                    DataBase.Entry(tB_Take_Course).State = EntityState.Deleted;
                    DataBase.SaveChanges();

                    DataBase = new DB_FWDEntities();
                    gridControl1.DataSource = DataBase.View_Take_Course.ToList();

                    ToastDel.Show();
                }
            }
            catch
            {
                ToastWaring.Lable_Text.Text = "لا يوجد شئ لحذفة";
                ToastWaring.Show();
            }

        }
    }
}
