using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Volanteer
{
    public partial class Form_Volanteer_Add : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_volunteer tb_volunteer = new TB_volunteer();
        public Form_Volanteer_Add()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext1 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext1.TB_Social_State.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                edit_volantee_so_st.Properties.DataSource = dbContext1.TB_Social_State.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext2 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext2.TB_Committee.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                edit_volantee_commit1.Properties.DataSource = dbContext2.TB_Committee.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext3 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext3.TB_Committee.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                edit_volantee_commt2.Properties.DataSource = dbContext3.TB_Committee.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext4 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext4.TB_Volunteer_Type.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                edit_volantee_type.Properties.DataSource = dbContext4.TB_Volunteer_Type.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());




            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext5 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext5.TBE_LOC.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                edit_volantee_add.Properties.DataSource = dbContext5.TBE_LOC.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext6 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext6.TBE_LOC.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    edit_volantee_addjop.Properties.DataSource = dbContext6.TBE_LOC.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void label13_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            try
            {
                tb_volunteer.volunteer_Name = edit_volantee_name.Text;
                tb_volunteer.volunteer_Phone = edit_volantee_phone.Text;
                tb_volunteer.volunteer_sol_st = Convert.ToInt32(edit_volantee_so_st.EditValue);
                tb_volunteer.volunteer_SSN = edit_volantee_ssn.Text;
                tb_volunteer.volunteer_Start_Date= edit_volantee_startDate.DateTimeOffset.DateTime;

                if (edit_volantee_tax.Text == ""|| edit_volantee_tax.Text == "0")
                    tb_volunteer.volunteer_Tax = 0.0;
                else 
                    tb_volunteer.volunteer_Tax =Convert.ToDouble(edit_volantee_tax.Text);

                tb_volunteer.volunteer_type = Convert.ToInt32(edit_volantee_type.EditValue);
                tb_volunteer.volunteer_type_num = member_num.Text;
                tb_volunteer.volunteer_Work_add = Convert.ToInt32(edit_volantee_addjop.EditValue);
                tb_volunteer.volunteer_Bairth = edit_volantee_bairth.DateTimeOffset.DateTime;
                tb_volunteer.volunteer_Add = Convert.ToInt32(edit_volantee_add.EditValue);
                tb_volunteer.volunteer_Jop = edit_volantee_jop.Text;
                tb_volunteer.volunteer_Department_1 = Convert.ToInt32(edit_volantee_commit1.EditValue);
                tb_volunteer.volunteer_Department_2 = Convert.ToInt32(edit_volantee_commt2.EditValue);
                tb_volunteer.volunteer_more_info = edit_volantee_det.Text;

                //  ToastDone.LbTitelAlterBox.Text = "تمت عملية التسجيل";


                DataBase.TB_volunteer.Add(tb_volunteer);
                DataBase.SaveChanges();


                ToastDone.Show();
                ClearFormData();
                // this.Close();

            }            
            catch (Exception ex)
            {
                ToastWaring.Lable_Text.Text = "An error occurred: " + ex.Message;
                ToastWaring.Show();
            }



        }

        private void Form_Volanteer_Add_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_FWDDataSet2066.TBE_LOC' table. You can move, or remove it, as needed.
        //    this.tBE_LOCTableAdapter.Fill(this.dB_FWDDataSet2066.TBE_LOC);
            // TODO: This line of code loads data into the 'dB_FWDDataSet2065.TB_Volunteer_Type' table. You can move, or remove it, as needed.
          //  this.tB_Volunteer_TypeTableAdapter.Fill(this.dB_FWDDataSet2065.TB_Volunteer_Type);
            // TODO: This line of code loads data into the 'dB_FWDDataSet2063.TB_Committee' table. You can move, or remove it, as needed.
          //  this.tB_CommitteeTableAdapter.Fill(this.dB_FWDDataSet2063.TB_Committee);
          //  // TODO: This line of code loads data into the 'dB_FWDDataSet2062.TB_Social_State' table. You can move, or remove it, as needed.
          ///  this.tB_Social_StateTableAdapter.Fill(this.dB_FWDDataSet2062.TB_Social_State);

        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }


        private void ClearFormData()
        {
            edit_volantee_name.Text = string.Empty;
            edit_volantee_phone.Text = string.Empty;
            edit_volantee_so_st.EditValue = 0;
            edit_volantee_ssn.Text = string.Empty;
            edit_volantee_startDate.DateTimeOffset = DateTimeOffset.Now;
            edit_volantee_tax.Text = string.Empty;
            edit_volantee_type.EditValue = 0;
            member_num.Text = string.Empty;
            edit_volantee_addjop.EditValue = 0;
            edit_volantee_bairth.DateTimeOffset = DateTimeOffset.Now;
            edit_volantee_add.EditValue = 0;
            edit_volantee_jop.Text = string.Empty;
            edit_volantee_commit1.EditValue = 0;
            edit_volantee_commt2.EditValue = 0;
            edit_volantee_det.Text = string.Empty;
        }
    }
}
