using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraGrid;
using DevExpress.XtraReports.UI;



namespace FWD.G_General_Report
{
    public partial class Form_General_Report_List : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_General_report tb_report = new TB_General_report();
        public Form_General_Report_List()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.View_General_report.LoadAsync().ContinueWith(loadTask =>
            {
                gridControl1.DataSource = dbContext.View_General_report.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            Reports.Report_General_Report Report = new Reports.Report_General_Report();
            int id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("General_report_ID"));
            
            tb_report = DataBase.TB_General_report.Where(x => x.General_report_ID == id).FirstOrDefault();

            Report.DataSource = tb_report;
            Report.ShowPreview();
            //   Report.ShowDesigner();
        }

        private void btn_ref_Click(object sender, EventArgs e)
        {
            UpDate_Data();
        }
        private void UpDate_Data()
        {
            DataBase = new DB_FWDEntities();
            gridControl1.DataSource = DataBase.TB_General_report.ToList();
        }

        private void btn_del_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("General_report_ID"));
            var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من عملية الحذف", MessageBoxButtons.YesNo);

            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            Toast.Toast_Del ToastDel = new Toast.Toast_Del();


            try
            {
                if (rs == DialogResult.Yes)
                {
                    tb_report = DataBase.TB_General_report.Where(x => x.General_report_ID == id).FirstOrDefault();
                    DataBase.Entry(tb_report).State = EntityState.Deleted;
                    DataBase.SaveChanges();
                    UpDate_Data();

                    ToastDel.Show();
                }
            }
            catch
            {
                ToastWaring.Lable_Text.Text = "لا يوجد شئ لحذفة";
                ToastWaring.Show();
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("General_report_ID"));
            Form_General_Report form_General_Report = new Form_General_Report();

            tb_report = DataBase.TB_General_report.Where(x => x.General_report_ID == id).FirstOrDefault();
            form_General_Report.id_report = id;
            form_General_Report.Add.Text = "تعديل";

            form_General_Report.edit_report_num.Text = Convert.ToString( tb_report.General_report_Number);
            form_General_Report.edit_report_table.Text = tb_report.General_report_table;
            form_General_Report.edit_report_dession.Text = tb_report.General_report_dessition;
            form_General_Report.edit_report_day.Text = tb_report.General_report_day;
            form_General_Report.edit_date.DateTime =Convert.ToDateTime( tb_report.General_report_date);
            form_General_Report.edit_report_start.Text = tb_report.General_report_start;
            form_General_Report.edit_report_end.Text = tb_report.General_report_end;


            form_General_Report.Show();
            

        }
    }
}
