using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
 



namespace FWD.G_Setting
{
    public partial class Form_DashBoard : Form
    {


        public Form_DashBoard()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
         

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {
        }

        private void Form_DashBoard_Load(object sender, EventArgs e){

        }

        private void flowLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            chartControl2.ClearCache();
            chartControl2.Series["Series 1"].Points.Add(new DevExpress.XtraCharts.SeriesPoint("ahmed", 1));
            chartControl2.Series["Series 1"].Points.Add(new DevExpress.XtraCharts.SeriesPoint("Ali", 50));
            chartControl2.Series["Series 1"].Points.Add(new DevExpress.XtraCharts.SeriesPoint("Kaled", 10));
            chartControl2.Series["Series 1"].Points.Add(new DevExpress.XtraCharts.SeriesPoint("Yasser", 3));

        }
    }

}
