using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Setting
{
    public partial class Form_resercher : Form
    {

        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_RES tb_res  = new TB_RES();

        public Form_resercher()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBE_LOC.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    edt_supp_add.Properties.DataSource = dbContext.TBE_LOC.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void label9_Click(object sender, EventArgs e)
        {

        }

        private void Btn_Add_Click(object sender, EventArgs e)
        {

            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();

            if (edt_supp_name.Text == "" || edt_supp_phone1.Text == "" ||  edt_supp_ssn.Text == "" || edt_supp_add.Text == "")
            {
                ToastWaring.Lable_Text.Text = "اكمل باقى البيانات";
                ToastWaring.Show();
            }
            else
            {

                tb_res.RES_Name= edt_supp_name.Text;
                tb_res.RES_Phone = edt_supp_phone1.Text;
                tb_res.RES_SSN = edt_supp_ssn.Text;
                tb_res.RES_Add= Convert.ToInt32(edt_supp_add.EditValue);


                DataBase.TB_RES.Add(tb_res);
                DataBase.SaveChanges();
                ToastDone.Text = "تمت اضافة مندوب";
                ToastDone.Show();
                clrear();
            }
           
          

        }


        private void clrear()
        {
            edt_supp_add.Text = "";
            edt_supp_name.Text = "";
            edt_supp_phone1.Text = "";
            edt_supp_ssn.Text = "";



        }
    }
}
