using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Setting
{
    public partial class Form_Addres_Add : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TBE_LOC tbe_loc = new TBE_LOC();
        public Form_Addres_Add()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBE_LOC.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.TBE_LOC.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            Toise.Toast_Wrong toast_Wrong = new Toise.Toast_Wrong();

            var rs = MessageBox.Show("تاكد من البيانات", "هل متاكد من ان البيانات صحيحة ؟ّ! لا يمكنك الحذف او التعديل ", MessageBoxButtons.YesNo);
            if (rs == DialogResult.Yes)
            {

                try{
                    if (Edit_Text_1.Text == ""|| Edit_Text_2.Text == "")
                    {
                        ToastWaring.Lable_Text.Text = "اكمل باقى البيانات";
                        ToastWaring.Show();
                    }
                    else
                    {
                        tbe_loc.LOC_Name = Edit_Text_1.Text;
                        tbe_loc.LOC_Key = Edit_Text_2.Text;




                        DataBase.TBE_LOC.Add(tbe_loc);
                        DataBase.SaveChanges();


                        ToastDone.Lable_Text.Text = "تمت الاضافة";
                        ToastDone.Show();
                        this.Close();
                    }
                }
                catch
                {
                    toast_Wrong.Lable_Text.Text = "حدث خطأ";
                    toast_Wrong.Show();

                }

            }
        }

        private void Edit_Text_2_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void Form_Addres_Add_Load(object sender, EventArgs e)
        {

        }
    }
}
