using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Setting
{
    public partial class Form_Helth_Add : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_Health_Status tb_Health_Status = new TB_Health_Status();
        public Form_Helth_Add()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Health_Status.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridSplitContainer1Grid.DataSource = dbContext.TB_Health_Status.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void Btn_Add_Click(object sender, EventArgs e)
        {
            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
           // Toise.Toast_Wrong toast_Wrong = new Toise.Toast_Wrong();

            var rs = MessageBox.Show("هل متاكد من ان البيانات صحيحة؟ّ! لا يمكنك الحذف او التعديل ", "تاكد من البيانات", MessageBoxButtons.YesNo);
            if (rs == DialogResult.Yes)
            {

                try
                {
                    if (Edit_Text_1.Text == "")
                    {
                        ToastWaring.Lable_Text.Text = "اضف الحالة التعليمة";
                        ToastWaring.Show();
                    }
                    else
                    {
                        tb_Health_Status.Health_Status_Name = Edit_Text_1.Text;

                        DataBase.TB_Health_Status.Add(tb_Health_Status);
                        DataBase.SaveChanges();


                        DataBase = new DB_FWDEntities();
                        gridSplitContainer1Grid.DataSource = DataBase.TB_Health_Status.ToList();

                        ToastDone.Lable_Text.Text = "تمت الاضافة";
                        ToastDone.Show();
                    }
                }
                catch
                {
                    ToastWaring.Lable_Text.Text = "حدث خطأ";
                    ToastWaring.Show();

                }
            }

        }
    }
}
