using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Doctors
{
    public partial class Form_Parmasist_Add : Form
    {
        DB_FWDEntities DataBase = new DB_FWDEntities();
        TB_Pharmasist_Info tb_Pharmasist_Info = new TB_Pharmasist_Info();
        public Form_Parmasist_Add()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.View_Pharmasist_Info.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.View_Pharmasist_Info.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext1 = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext1.TBE_LOC.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    Edit_Add.Properties.DataSource = dbContext1.TBE_LOC.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            Toise.Toast_Wrong toast_Wrong = new Toise.Toast_Wrong();

            var rs = MessageBox.Show("تاكد من البيانات", "هل متاكد من ان البيانات صحيحة ؟ّ! لا يمكنك الحذف او التعديل ", MessageBoxButtons.YesNo);
            if(rs == DialogResult.Yes)
            try
            {
                if (edt_doc_name.Text == ""  )
                {
                    ToastWaring.Lable_Text.Text = "اكمل باقى البيانات";
                    ToastWaring.Show();
                }
                else
                {
                    tb_Pharmasist_Info.Pharmasist_Name = edt_doc_name.Text;
                    tb_Pharmasist_Info.Pharmasist_Add = Convert.ToInt32(Edit_Add.EditValue);

                    DataBase.TB_Pharmasist_Info.Add(tb_Pharmasist_Info);
                    DataBase.SaveChanges();


                    ToastDone.Lable_Text.Text = "تمت الاضافة";
                    ToastDone.Show();
                    this.Close();
                }
            }
            catch
            {
                toast_Wrong.Lable_Text.Text = "حدث خطأ";
                toast_Wrong.Show();

            }
        }

        private void Form_Parmasist_Add_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'dB_FWDDataSet2084.TBE_LOC' table. You can move, or remove it, as needed.
            this.tBE_LOCTableAdapter1.Fill(this.dB_FWDDataSet2084.TBE_LOC);

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
