using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace FWD.G_Users
{
    public partial class Form_User_Add : Form
    {
       // DB_FWDEntities DataBase = new DB_FWDEntities();
       // TB_Emploee tb_emploee = new TB_Emploee();
        TB_User_Permitions tb_permation = new TB_User_Permitions();
        private bool cheekEmail = false;
        private bool cheekPass = false;
        private bool cheekPass2 = false;
        public Form_User_Add()
        {
            InitializeComponent();
            PassWord2.Properties.PasswordChar = '*'; // Set password character
            PassWord1.Properties.PasswordChar = '*'; // Set password character
                                                     // This line of code is generated by Data Source Configuration Wizard
                                                     // Instantiate a new DBContext
            FWD.DB_FWDEntities dbContext = new FWD.DB_FWDEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Emploee_Roll.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    edit_user_roll.Properties.DataSource = dbContext.TB_Emploee_Roll.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void cheekImage(int val)
        {
            if (val == 1){
                False.Visible = false;
                True.Visible = true;
            }
            else
            {
                False.Visible = true;
                True.Visible = false;

            }
        }

        private void cheekImage2(int val)
        {
            if (val == 1)
            {
                FalseP1.Visible = false;
                TrueP1.Visible = true;
            }
            else
            {
                FalseP1.Visible = true;
                TrueP1.Visible = false;

            }
        }

        private void cheekImage3(int val)
        {
            if (val == 1)
            {
                FalseP2.Visible = false;
                TrueP2.Visible = true;
            }
            else
            {
                FalseP2.Visible = true;
                TrueP2.Visible = false;

            }
        }
        private void edt_tool_give_recever_EditValueChanged(object sender, EventArgs e)
        {
            string x = edit_user_username.Text;
            Email_Add.Text =x + "@ElNada.com";
            if (x== " _")Email_Add.Text ="";
            if (x.Length >= 5 && x.Length <= 15)
            {
                cheekEmail = true;
                exceptionEmail.Visible = false;
                Email_Add.Visible = true;
                cheekImage(1);
            }
            else
            {
                    cheekEmail = false;
                if(x.Length < 5)
                {

                    exceptionEmail.Text = "الاسم قصير";
                    exceptionEmail.Visible = true;
                    Email_Add.Visible = false;
                    cheekImage(2);
                }
                else
                {
                    exceptionEmail.Text = "الاسم طويل";
                    exceptionEmail.Visible = true;
                    Email_Add.Visible = false;
                    cheekImage(2);
                }

            }



        }

        private void textEdit1_EditValueChanged(object sender, EventArgs e) {
            string x = PassWord1.Text;


            if (x.Length >= 5 && x.Length <= 15)
            {
                cheekPass = true;
                cheekImage2(1);
                exceptionPasss1.Visible = false;
            }
            else
            {
                cheekPass = false;
                if (x.Length < 5)
                {
                    exceptionPasss1.Text = "الرقم قصير";
                    exceptionPasss1.Visible = true;
                    cheekImage2(2);
                }
                else
                {
                    exceptionPasss1.Text = "الرقم طويل";
                    exceptionPasss1.Visible = true;

                    cheekImage2(2);
                }

            }
        }

        private void Form_User_Add_Load(object sender, EventArgs e)
        {
            TrueP1.Visible = false;
            TrueP2.Visible = false;
            True.Visible = false;
            FalseP1.Visible = false;
            FalseP2.Visible = false;
            False.Visible = false;
            Email_Add.Visible = false;

        }

        private void textEdit2_EditValueChanged(object sender, EventArgs e)
        {
            if (PassWord1.Text == PassWord2.Text)
            {
                cheekImage3(1);
                PassTex.Visible = false;
                cheekPass2 = true;

            }
            else
            {
                cheekPass2 = false;
                cheekImage3(3);
                PassTex.Visible = true;
            }

        }

        private void edt_tool_give_pationt_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            DB_FWDEntities DataBase = new DB_FWDEntities();

            TB_Emploee tb_emploee = new TB_Emploee();

            Toise.Toast_Done ToastDone = new Toise.Toast_Done();
            Toise.Toast_Waring ToastWaring = new Toise.Toast_Waring();
            try{
                if (cheekPass && cheekPass2 && cheekEmail)
                {
                    tb_emploee.Emploee_Name = edit_user_name.Text;
                    tb_emploee.Emploee_UserName = edit_user_username.Text;
                    tb_emploee.Emploee_Roll =Convert.ToInt32( edit_user_roll.EditValue);
                    tb_emploee.Emploee_phone = edit_user_Phone.Text;
                    tb_emploee.Emploee_Password = PassWord1.Text;
                    tb_emploee.Emploee_permitions = premetions();
                    tb_emploee.Emploee_Roll_login_State = "false";

                    DataBase.TB_Emploee.Add(tb_emploee);
                    DataBase.SaveChanges();
                    ToastDone.Show();
                }
                else
                {
                    ToastWaring.Lable_Text.Text = "تاكد من البيانات";
                    ToastWaring.Show();


                }

                
            }
            catch
            {
                ToastWaring.Lable_Text.Text = "اسم المستخدم مكرر";
                ToastWaring.Show();
            }
        }

        private void checkEdit48_CheckedChanged(object sender, EventArgs e)
        {

        }

        private void checkEdit63_CheckedChanged(object sender, EventArgs e)
        {

        }



        private int premetions(){
            DB_FWDEntities DataBase = new DB_FWDEntities();
            TB_User_Permitions tb_permation = new TB_User_Permitions();

            tb_permation.Category_add = category_add.Checked;
            tb_permation.Category_del = category_del.Checked;
            tb_permation.Category_edit = category_edit.Checked;
            tb_permation.Category_list = category_list.Checked;
            tb_permation.Course_add = course_add.Checked;
            tb_permation.Course_del = course_del.Checked;
            tb_permation.Course_edit = course_edit.Checked;
            tb_permation.Course_list = course_list.Checked;
            tb_permation.Doctor_add = doctor_add.Checked;
            tb_permation.Doctor_del = doctor_del.Checked;
            tb_permation.Doctor_doc_add = doctor_doc_add.Checked;
            tb_permation.Doctor_doc_del = doctor_doc_add.Checked;
            tb_permation.Donation_del = donation_del.Checked;
            tb_permation.Donation_List = donation_List.Checked;
            tb_permation.General_backup = general_backup.Checked;
            tb_permation.General_report_add = general_report_add.Checked;
            tb_permation.General_report_del = general_report_del.Checked;
            tb_permation.General_report_edit = general_report_edit.Checked;
            tb_permation.General_report_list = general_report_list.Checked;
            tb_permation.General_server = general_server.Checked;
            tb_permation.General_user_add = general_user_add.Checked;
            tb_permation.General_user_list = general_user_list.Checked;
            tb_permation.Midical_List_add = midical_list_add.Checked;
            tb_permation.Midical_List_del = midical_list_del.Checked;
            tb_permation.Midical_List_edit = midical_list_edit.Checked;
            tb_permation.Midical_List_list = midical_list_list.Checked;
            tb_permation.Midical_Receve_add = midical_receve_add.Checked;
            tb_permation.Midical_Receve_del = midical_receve_del.Checked;
            tb_permation.Midical_Receve_edit = midical_receve_edit.Checked;
            tb_permation.Midical_Receve_return = midical_receve_return.Checked;
            tb_permation.Pharmasy_add = pharmasy_add.Checked;
            tb_permation.Pharmasy_del = pharmasy_del.Checked;
            tb_permation.Pharmasy_doc_add = pharmasy_doc_add.Checked;
            tb_permation.Pharmasy_doc_del = pharmasy_doc_del.Checked;
            tb_permation.Poket_del = poket_del.Checked;
            tb_permation.Poket_list = poket_List.Checked;
            tb_permation.Receve_add = receve_add.Checked;
            tb_permation.Receve_del = receve_del.Checked;
            tb_permation.Receve_list = receve_list.Checked;
            tb_permation.Record_add = recovrd_add.Checked;
            tb_permation.Record_del = recovrd_del.Checked;
            tb_permation.Record_edit = recovrd_edit.Checked;
            tb_permation.Record_lisr = recovrd_list.Checked;
            tb_permation.Supp_add = supp_add.Checked;
            tb_permation.Supp_del = supp_del.Checked;
            tb_permation.Supp_edit = supp_edit.Checked;
            tb_permation.Supp_list=supp_list.Checked;
            tb_permation.Trainer_add = trainer_add.Checked;
            tb_permation.Trainer_del = trainer_del.Checked;
            tb_permation.Trainer_edit = trainer_edit.Checked;
            tb_permation.Trainer_list = trainer_list.Checked;
            tb_permation.volanteer_add = volanteer_add.Checked;
            tb_permation.volanteer_edit = volanteer_edit.Checked;
            tb_permation.Volanteer_list = volanteer_list.Checked;
            tb_permation.volanteer_subscription = volanteer_supsscription.Checked;
            tb_permation.Wat_list_add = wat_list_add.Checked;
            tb_permation.Wat_list_del = wat_list_del.Checked;
            tb_permation.Wat_list_edit = wat_list_edit.Checked;
            tb_permation.Wat_list_list = wat_list_List.Checked;
            tb_permation.Donation_Donnner = donation_doner.Checked;
            tb_permation.General_home = general_home.Checked;
            tb_permation.General_programe_set = general_seting.Checked;
            tb_permation.General_user_del = general_user_del.Checked;
            tb_permation.General_user_list = general_user_list.Checked;

            DataBase.TB_User_Permitions.Add(tb_permation);
            DataBase.SaveChanges();
            int primaryKeyValue = tb_permation.Permition_ID;
            return primaryKeyValue;
        }
    }
}
